language: objective-c
osx_image: xcode8
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
install: true # skip cocoapods; all dependencies are already in the repo
script: make test
notifications:
  email:
    - nolan@nolanw.ca
    - liamwestby@icloud.com
